# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/rpcmeta.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63ommon/rpcmeta.proto\x12\x12\x64\x61ta.speech.common\"\xda\x01\n\x0bRequestMeta\x12\x1a\n\x08\x45ndpoint\x18\x01 \x01(\tR\x08\x65ndpoint\x12\x17\n\x06\x41ppKey\x18\x02 \x01(\tR\x07\x61pp_key\x12\x15\n\x05\x41ppID\x18\x03 \x01(\tR\x06\x61pp_id\x12\x1f\n\nResourceID\x18\x04 \x01(\tR\x0bresource_id\x12#\n\x0c\x43onnectionID\x18\x05 \x01(\tR\rconnection_id\x12\x1d\n\tSessionID\x18\x06 \x01(\tR\nsession_id\x12\x1a\n\x08Sequence\x18\x07 \x01(\x05R\x08sequence\"=\n\x0b\x42illingItem\x12\x12\n\x04Unit\x18\x01 \x01(\tR\x04unit\x12\x1a\n\x08Quantity\x18\x02 \x01(\x02R\x08quantity\"\x84\x01\n\x07\x42illing\x12\x35\n\x05Items\x18\x01 \x03(\x0b\x32\x1f.data.speech.common.BillingItemR\x05items\x12#\n\x0c\x44urationMsec\x18\x02 \x01(\x03R\rduration_msec\x12\x1d\n\tWordCount\x18\x03 \x01(\x03R\nword_count\"\xcc\x01\n\x0cResponseMeta\x12\x1d\n\tSessionID\x18\x01 \x01(\tR\nsession_id\x12\x1a\n\x08Sequence\x18\x02 \x01(\x05R\x08sequence\x12\x1f\n\nStatusCode\x18\x03 \x01(\x05R\x0bstatus_code\x12\x18\n\x07Message\x18\x04 \x01(\tR\x07message\x12:\n\x07\x42illing\x18\x05 \x01(\x0b\x32\x1b.data.speech.common.BillingH\x00R\x07\x62illing\x88\x01\x01\x42\n\n\x08_Billingb\x06proto3')



_REQUESTMETA = DESCRIPTOR.message_types_by_name['RequestMeta']
_BILLINGITEM = DESCRIPTOR.message_types_by_name['BillingItem']
_BILLING = DESCRIPTOR.message_types_by_name['Billing']
_RESPONSEMETA = DESCRIPTOR.message_types_by_name['ResponseMeta']
RequestMeta = _reflection.GeneratedProtocolMessageType('RequestMeta', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTMETA,
  '__module__' : 'common.rpcmeta_pb2'
  # @@protoc_insertion_point(class_scope:data.speech.common.RequestMeta)
  })
_sym_db.RegisterMessage(RequestMeta)

BillingItem = _reflection.GeneratedProtocolMessageType('BillingItem', (_message.Message,), {
  'DESCRIPTOR' : _BILLINGITEM,
  '__module__' : 'common.rpcmeta_pb2'
  # @@protoc_insertion_point(class_scope:data.speech.common.BillingItem)
  })
_sym_db.RegisterMessage(BillingItem)

Billing = _reflection.GeneratedProtocolMessageType('Billing', (_message.Message,), {
  'DESCRIPTOR' : _BILLING,
  '__module__' : 'common.rpcmeta_pb2'
  # @@protoc_insertion_point(class_scope:data.speech.common.Billing)
  })
_sym_db.RegisterMessage(Billing)

ResponseMeta = _reflection.GeneratedProtocolMessageType('ResponseMeta', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEMETA,
  '__module__' : 'common.rpcmeta_pb2'
  # @@protoc_insertion_point(class_scope:data.speech.common.ResponseMeta)
  })
_sym_db.RegisterMessage(ResponseMeta)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUESTMETA._serialized_start=45
  _REQUESTMETA._serialized_end=263
  _BILLINGITEM._serialized_start=265
  _BILLINGITEM._serialized_end=326
  _BILLING._serialized_start=329
  _BILLING._serialized_end=461
  _RESPONSEMETA._serialized_start=464
  _RESPONSEMETA._serialized_end=668
# @@protoc_insertion_point(module_scope)
